# Analysing a numpy array

In [1]:
import numpy as np

In [2]:
c = np.random.randint(10,50,(3,5))
print(c)

[[22 40 17 31 43]
 [37 10 31 16 31]
 [35 17 19 16 12]]


1.Array shape 

In [3]:
print(c.shape)

(3, 5)


2.Array Dimensions

In [4]:
print(c.ndim)

2


since it is a 2 dimensional array with rows and colunms

3. size , number of elements in a array

In [5]:
print(c.size)

15


4. checking the data type of the values in the array

In [6]:
print(c.dtype)

int64


# Mathematical Operations On a np Array

In [7]:
list1= [1,2,3,4]
list2 = [5,6,7,8]
print(list1 + list2) # this concatinate the two list not add the lement of the list

[1, 2, 3, 4, 5, 6, 7, 8]


# in np array 

In [11]:
a = np.random.randint(10,50,(5,5))
b = np.random.randint(10,30,(5,5))
print(a)
print(b)
print(a+b) # or print(np.add(a,b))
print(a-b) # or print(np.subtract(a,b))
print(a*b) # or print(np.multiply(a,b))
print(a/b) # or print(np.divide(a,b))

[[16 12 33 35 33]
 [10 38 17 32 14]
 [47 49 25 38 24]
 [38 39 14 28 34]
 [24 49 36 37 29]]
[[18 12 28 29 22]
 [29 12 19 18 18]
 [21 11 23 10 18]
 [16 10 19 21 12]
 [17 13 17 15 19]]
[[34 24 61 64 55]
 [39 50 36 50 32]
 [68 60 48 48 42]
 [54 49 33 49 46]
 [41 62 53 52 48]]
[[ -2   0   5   6  11]
 [-19  26  -2  14  -4]
 [ 26  38   2  28   6]
 [ 22  29  -5   7  22]
 [  7  36  19  22  10]]
[[ 288  144  924 1015  726]
 [ 290  456  323  576  252]
 [ 987  539  575  380  432]
 [ 608  390  266  588  408]
 [ 408  637  612  555  551]]
[[0.88888889 1.         1.17857143 1.20689655 1.5       ]
 [0.34482759 3.16666667 0.89473684 1.77777778 0.77777778]
 [2.23809524 4.45454545 1.08695652 3.8        1.33333333]
 [2.375      3.9        0.73684211 1.33333333 2.83333333]
 [1.41176471 3.76923077 2.11764706 2.46666667 1.52631579]]
