# Array Manipulation

In [1]:
import numpy as np

In [2]:
array = np.random.randint(10,50,(3,3))
print(array)
print(array.shape)

[[16 35 42]
 [43 42 37]
 [35 23 21]]
(3, 3)


1. Transpose

In [3]:
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[16 43 35]
 [35 42 23]
 [42 37 21]]
(3, 3)


or

In [4]:
tran2 = array.T
print(tran2)
print(tran2.shape)

[[16 43 35]
 [35 42 23]
 [42 37 21]]
(3, 3)


2.Reshaping an array

In [5]:
a = np.random.randint(10,30,(3,4))
print(a)
print(a.shape)

[[24 15 19 24]
 [26 14 14 14]
 [23 13 28 16]]
(3, 4)


In [6]:
b = a.reshape(4,3)
print(b)
print(b.shape)

[[24 15 19]
 [24 26 14]
 [14 14 23]
 [13 28 16]]
(4, 3)
