Initial placeholader in numpy array
#Matrix

In [1]:
!pip install numpy

In [2]:
import numpy as np

1. Creating a numpy array of zeros

In [4]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


2.creating a numpy array of ones

In [5]:
y = np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3.array of any perticular value

In [6]:
z = np.full((3,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


4. creating an identity matrix

In [7]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


5.Creating a numpy array with random numbers (value remain from 0 to 1)

In [8]:
b = np.random.random((3,4))
print(b)

[[0.29001229 0.95640162 0.44920018 0.10546176]
 [0.98425051 0.80186107 0.5861787  0.80060056]
 [0.97368244 0.54620938 0.8187017  0.27771943]]


6.Creating an array with random integer values within a specific range

In [11]:
c = np.random.randint(10,100,(3,5))
print(c)

[[76 72 18 61 76]
 [69 31 31 25 64]
 [69 93 21 91 92]]


#Array

1.Array with evenly spaced values

In [13]:
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


2.Array of evenly spaced value by specifying the steps

In [14]:
e = np.arange(10,30,5)
print(c)

[[76 72 18 61 76]
 [69 31 31 25 64]
 [69 93 21 91 92]]


# converting a list to a numpy array

In [15]:
list2 = [1,5,3,66,46,47,44]
np_array = np.asarray(list2)
print(np_array)
print(type(np_array))

[ 1  5  3 66 46 47 44]
<class 'numpy.ndarray'>
